# Generated by Django 3.2.15 on 2022-08-10 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('username', models.TextField(blank=True, max_length=255)),
                ('current_weight', models.PositiveIntegerField(max_length=2)),
                ('goal_weight', models.PositiveIntegerField(max_length=2)),
                ('weight_private', models.BooleanField(default=False)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(default='../user-logged_giqn26.svg', upload_to='images/')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
